In [19]:
import pandas as pd
import matplotlib.pyplot as plt
import datetime as dt
from datetime import datetime, timedelta, date
import numpy as np
import warnings
warnings.filterwarnings('ignore')
import sqlite3

In [2]:
pip install dask

Requirement already satisfied: dask in /opt/anaconda3/lib/python3.13/site-packages (2025.2.0)
Requirement already satisfied: click>=8.1 in /opt/anaconda3/lib/python3.13/site-packages (from dask) (8.1.8)
Requirement already satisfied: cloudpickle>=3.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from dask) (3.0.0)
Requirement already satisfied: fsspec>=2021.09.0 in /opt/anaconda3/lib/python3.13/site-packages (from dask) (2025.3.2)
Requirement already satisfied: packaging>=20.0 in /opt/anaconda3/lib/python3.13/site-packages (from dask) (24.2)
Requirement already satisfied: partd>=1.4.0 in /opt/anaconda3/lib/python3.13/site-packages (from dask) (1.4.2)
Requirement already satisfied: pyyaml>=5.3.1 in /opt/anaconda3/lib/python3.13/site-packages (from dask) (6.0.2)
Requirement already satisfied: toolz>=0.10.0 in /opt/anaconda3/lib/python3.13/site-packages (from dask) (1.0.0)
Requirement already satisfied: locket in /opt/anaconda3/lib/python3.13/site-packages (from partd>=1.4.0->dask) (1.0.0)
Note: you may need to restart the kernel to use updated packages.

In [21]:
import dask.bag as db
import json
import dask.dataframe as dd

## Converting goodreads_romance_books from json to csv

In [4]:
json_bag = db.read_text('goodreads_books_romance.json').map(json.loads)
print(json_bag.take(3))

({'isbn': '', 'text_reviews_count': '4', 'series': [], 'country_code': 'US', 'language_code': '', 'popular_shelves': [{'count': '4', 'name': 'to-read'}, {'count': '1', 'name': 'ibooks'}, {'count': '1', 'name': 'favorite-authors'}, {'count': '1', 'name': 'may-2017-dr-reads'}, {'count': '1', 'name': 'sports-romance'}, {'count': '1', 'name': 'series-i-like'}, {'count': '1', 'name': 'romance'}, {'count': '1', 'name': 'favorites'}, {'count': '1', 'name': 'f-f'}, {'count': '1', 'name': 'hockey-romance'}, {'count': '1', 'name': 'ebook'}], 'asin': '', 'is_ebook': 'true', 'average_rating': '3.86', 'kindle_asin': '', 'similar_books': [], 'description': "Secrets. Sometimes keeping them in confidence is a good thing. Other times secrets can slowly allow a woman's soul to rot.\nWhitney Beaupre has been hiding a big secret for years, one that's beginning to wear her down both on and off the ice. Pretending to be something she's not is exhausting. Wanting to be free but afraid to break out of her prison is terrifying. Seeking love but then hiding from it is crushing to the spirit, yet Whitney feels compelled to keep living the lie. Until the night Hannah Kym appears in her life. Whitney's attraction to Hannah is deep, fierce, and instantaneous. The Temple art major is everything Whitney has dreamed of and more. But those old fears keep clawing at the Venom center, keeping her locked in the closet despite the passion and affection she feels for Hannah.\nCan love finally break the shackles holding Whitney's heart and soul captive?", 'format': 'ebook', 'link': 'https://www.goodreads.com/book/show/34883016-playmaker', 'authors': [{'author_id': '5807700', 'role': ''}], 'publisher': 'Gone Writing Publishing', 'num_pages': '', 'publication_day': '3', 'isbn13': '9781370889471', 'publication_month': '5', 'edition_information': '', 'publication_year': '2017', 'url': 'https://www.goodreads.com/book/show/34883016-playmaker', 'image_url': 'https://images.gr-assets.com/books/1493525974m/34883016.jpg', 'book_id': '34883016', 'ratings_count': '5', 'work_id': '56135087', 'title': 'Playmaker: A Venom Series Novella', 'title_without_series': 'Playmaker: A Venom Series Novella'}, {'isbn': '', 'text_reviews_count': '21', 'series': ['811663'], 'country_code': 'US', 'language_code': 'en-US', 'popular_shelves': [{'count': '598', 'name': 'to-read'}, {'count': '28', 'name': 'currently-reading'}, {'count': '14', 'name': 'paranormal'}, {'count': '10', 'name': 'shifters'}, {'count': '10', 'name': 'paranormal-romance'}, {'count': '5', 'name': 'romance'}, {'count': '5', 'name': 'arc'}, {'count': '4', 'name': 'carrie-ann-ryan'}, {'count': '4', 'name': 'shapeshifters'}, {'count': '3', 'name': 'series'}, {'count': '3', 'name': 'fantasy'}, {'count': '3', 'name': 'kindle'}, {'count': '2', 'name': 'to-read-paranormal'}, {'count': '2', 'name': 'favorites'}, {'count': '2', 'name': 'phoenix'}, {'count': '2', 'name': 'books-i-have'}, {'count': '2', 'name': 'nook'}, {'count': '2', 'name': '2016-books-read'}, {'count': '2', 'name': 'contemporary'}, {'count': '2', 'name': 'ebook'}, {'count': '2', 'name': 'dragons'}, {'count': '2', 'name': 'ryan-carrie-ann'}, {'count': '2', 'name': 'dantes-circle'}, {'count': '2', 'name': 'supernatural'}, {'count': '1', 'name': 'my-owned-books'}, {'count': '1', 'name': 'shapeshifters-all-species'}, {'count': '1', 'name': 'interspecies-forbidden-fated-mate'}, {'count': '1', 'name': 'fated-mates-all-kinds'}, {'count': '1', 'name': 'ttp-proj'}, {'count': '1', 'name': 'tbr-my-books-hanging-out-on-kindle'}, {'count': '1', 'name': 're-reading-worthy'}, {'count': '1', 'name': 'pnrm-pnranthologies'}, {'count': '1', 'name': 'fantasy-romance'}, {'count': '1', 'name': 'sub-genre-pnr'}, {'count': '1', 'name': 'no-thanks'}, {'count': '1', 'name': 'have-not-read'}, {'count': '1', 'name': 'f-shifters'}, {'count': '1', 'name': '0-my-library-of-books'}, {'count': '1', 'name': '0-books-w-audio-companion'}, {'count': '1', 'name': 'tbr'}, {'count': '1', 'name': 'itunes'}, {'count': '1', 'name': 'p-q-r-s'}, {'count': '1', 'name': 'pick-fantasy'}, {'count': '1', 'name': 'para-world'}, {'count': '1', 'name': 'flightsfantasy'}, {'count': '1', 'name': '1234'}, {'count': '1', 'name': '100000'}, {'count': '1', 'name': '100'}, {'count': '1', 'name': 'multi-paranormal-species'}, {'count': '1', 'name': 'i-own-a-copy'}, {'count': '1', 'name': 'dl'}, {'count': '1', 'name': 'audio'}, {'count': '1', 'name': 'fave-fantasy'}, {'count': '1', 'name': 'kindle-shelfari'}, {'count': '1', 'name': 'thriller'}, {'count': '1', 'name': 'suspense'}, {'count': '1', 'name': 'netgalley'}, {'count': '1', 'name': 'adult'}, {'count': '1', 'name': 'on-kindle'}, {'count': '1', 'name': 'book-challenge-2017'}, {'count': '1', 'name': 'werewolves'}, {'count': '1', 'name': 'uninteresting'}, {'count': '1', 'name': 'strong-heroines'}, {'count': '1', 'name': 'singel-parent'}, {'count': '1', 'name': 'gentle-hero'}, {'count': '1', 'name': 'owned'}, {'count': '1', 'name': 'pub-may'}, {'count': '1', 'name': 'secrect-baby'}, {'count': '1', 'name': 'second-chance'}, {'count': '1', 'name': 'books-from-carrie-ann'}, {'count': '1', 'name': '3-paranormal-series'}, {'count': '1', 'name': 'comptr-nook'}, {'count': '1', 'name': 'a-books-want-to-read'}, {'count': '1', 'name': 'x-pub-2016'}, {'count': '1', 'name': 'books-to-buy'}, {'count': '1', 'name': 'para-fantasy-romance'}, {'count': '1', 'name': 'kindle-ebooks-i-have-read'}, {'count': '1', 'name': 'title-p'}, {'count': '1', 'name': 'pages-100-150'}, {'count': '1', 'name': 'read-mee'}, {'count': '1', 'name': 'on-my-shelf'}, {'count': '1', 'name': 'audio-book'}, {'count': '1', 'name': 'complete-unfinished-series-owned'}, {'count': '1', 'name': 'giveaway-entry'}, {'count': '1', 'name': 'received-audio-book'}, {'count': '1', 'name': 'received'}, {'count': '1', 'name': '01-books'}, {'count': '1', 'name': 'wolves'}, {'count': '1', 'name': 'wizards'}, {'count': '1', 'name': 'succubus'}, {'count': '1', 'name': 'siren'}, {'count': '1', 'name': 'pixie'}, {'count': '1', 'name': 'n-ok'}, {'count': '1', 'name': 'n-gregory-salinas'}, {'count': '1', 'name': 'mermen'}, {'count': '1', 'name': 'lion'}, {'count': '1', 'name': 'feline'}, {'count': '1', 'name': 'fae'}, {'count': '1', 'name': 'djinn'}, {'count': '1', 'name': 'demons'}], 'asin': 'B01BLJGA9S', 'is_ebook': 'true', 'average_rating': '4.23', 'kindle_asin': 'B01BLJGA9S', 'similar_books': ['25515353', '20483269', '25650829', '18913492', '22578299', '25781561', '29518816', '20958132', '21854392', '27505924', '25205453'], 'description': '', 'format': '', 'link': 'https://www.goodreads.com/book/show/29074693-prowled-darkness', 'authors': [{'author_id': '5360266', 'role': ''}], 'publisher': '', 'num_pages': '', 'publication_day': '', 'isbn13': '', 'publication_month': '', 'edition_information': '', 'publication_year': '', 'url': 'https://www.goodreads.com/book/show/29074693-prowled-darkness', 'image_url': 'https://s.gr-assets.com/assets/nophoto/book/111x148-bcc042a9c91a29c1d680899eff700a03.png', 'book_id': '29074693', 'ratings_count': '149', 'work_id': '46079519', 'title': "Prowled Darkness (Dante's Circle, #7)", 'title_without_series': "Prowled Darkness (Dante's Circle, #7)"}, {'isbn': '1597371289', 'text_reviews_count': '8', 'series': [], 'country_code': 'US', 'language_code': 'eng', 'popular_shelves': [{'count': '16215', 'name': 'classics'}, {'count': '7070', 'name': 'to-read'}, {'count': '4564', 'name': 'fiction'}, {'count': '4279', 'name': 'favorites'}, {'count': '3125', 'name': 'romance'}, {'count': '2750', 'name': 'classic'}, {'count': '1942', 'name': 'books-i-own'}, {'count': '1503', 'name': 'owned'}, {'count': '1277', 'name': 'jane-austen'}, {'count': '996', 'name': 'historical-fiction'}, {'count': '993', 'name': 'clàssics'}, {'count': '904', 'name': 'literature'}, {'count': '665', 'name': 'historical'}, {'count': '575', 'name': 'kindle'}, {'count': '560', 'name': 'owned-books'}, {'count': '530', 'name': 'favourites'}, {'count': '497', 'name': '19th-century'}, {'count': '478', 'name': 'classic-literature'}, {'count': '445', 'name': 'british'}, {'count': '419', 'name': 'novels'}, {'count': '398', 'name': '1001-books'}, {'count': '369', 'name': 'austen'}, {'count': '350', 'name': 'currently-reading'}, {'count': '340', 'name': 'british-literature'}, {'count': '329', 'name': 'historical-romance'}, {'count': '309', 'name': 'classics-to-read'}, {'count': '305', 'name': 'adult'}, {'count': '282', 'name': 'book-club'}, {'count': '282', 'name': 'regency'}, {'count': '279', 'name': 'england'}, {'count': '269', 'name': 'to-buy'}, {'count': '265', 'name': 'english'}, {'count': '250', 'name': 'adult-fiction'}, {'count': '248', 'name': 'my-books'}, {'count': '244', 'name': 'my-library'}, {'count': '243', 'name': 'audiobook'}, {'count': '236', 'name': 'library'}, {'count': '235', 'name': 'rory-gilmore-reading-challenge'}, {'count': '235', 'name': 'chick-lit'}, {'count': '230', 'name': 'i-own'}, {'count': '219', 'name': 'default'}, {'count': '216', 'name': 'audiobooks'}, {'count': '215', 'name': 'my-ebooks'}, {'count': '207', 'name': 'classic-fiction'}, {'count': '206', 'name': '1001'}, {'count': '202', 'name': 'novel'}, {'count': '200', 'name': 'ebooks'}, {'count': '193', 'name': 're-read'}, {'count': '173', 'name': 'classic-lit'}, {'count': '171', 'name': 'english-literature'}, {'count': '170', 'name': 'school'}, {'count': '168', 'name': 'to-read-classics'}, {'count': '163', 'name': 'literary-fiction'}, {'count': '161', 'name': 'own-it'}, {'count': '152', 'name': 'audio'}, {'count': '150', 'name': 'brit-lit'}, {'count': '142', 'name': '1001-books-to-read-before-you-die'}, {'count': '140', 'name': 'all-time-favorites'}, {'count': '139', 'name': 'the-classics'}, {'count': '134', 'name': 'tbr'}, {'count': '133', 'name': 'unfinished'}, {'count': '128', 'name': 'british-lit'}, {'count': '127', 'name': 'rory-gilmore-challenge'}, {'count': '116', 'name': 'general-fiction'}, {'count': '116', 'name': 'on-my-shelf'}, {'count': '107', 'name': 'women'}, {'count': '107', 'name': 'e-book'}, {'count': '105', 'name': 'did-not-finish'}, {'count': '103', 'name': 'abandoned'}, {'count': '98', 'name': 'humor'}, {'count': '98', 'name': 'e-books'}, {'count': '97', 'name': 'rory-gilmore'}, {'count': '96', 'name': 'female-authors'}, {'count': '95', 'name': 'kindle-books'}, {'count': '94', 'name': 'romantic'}, {'count': '94', 'name': 'reread'}, {'count': '93', 'name': 'read-in-2015'}, {'count': '93', 'name': 'female-author'}, {'count': '92', 'name': 'classici'}, {'count': '91', 'name': 'favorite-books'}, {'count': '90', 'name': 'own-to-read'}, {'count': '90', 'name': 'stand-alone'}, {'count': '89', 'name': 'on-hold'}, {'count': '89', 'name': 'my-bookshelf'}, {'count': '89', 'name': 'literary'}, {'count': '88', 'name': 'home-library'}, {'count': '88', 'name': 'love'}, {'count': '85', 'name': 'to-re-read'}, {'count': '84', 'name': 'tbr-pile'}, {'count': '84', 'name': 'audio-book'}, {'count': '84', 'name': 'drama'}, {'count': '83', 'name': 'history'}, {'count': '83', 'name': 'victorian'}, {'count': '82', 'name': 'read-in-2016'}, {'count': '82', 'name': 'wish-list'}, {'count': '82', 'name': 'audio-books'}, {'count': '81', 'name': 'bookshelf'}, {'count': '80', 'name': 'read-in-2017'}, {'count': '80', 'name': 'dnf'}, {'count': '79', 'name': 'personal-library'}], 'asin': '', 'is_ebook': 'false', 'average_rating': '3.99', 'kindle_asin': 'B0083Z3O8Y', 'similar_books': ['31242', '374380', '20564', '383206', '7891', '6335178', '31175', '372811', '77395', '856190', '686278', '5797', '32110', '3102', '264', '99329', '31667'], 'description': "The funny and heartwarming story of a young lady whose zeal, snobbishness, and self-satisfaction lead to several errors in judgment\nEmma takes Harriet Smith, a young woman previously unknown to good society, under her wing, scheming for her advancement through an advantageous marriage. Her efforts to find Harriet a suitor occupy all of Emma's time. However, in the midst of her often fumbled attempts, she settles on a most unlikely union with her own constant critic: Mr. Knightly.\nThis novel is part of Brilliance Audio's extensive Classic Collection, bringing you timeless masterpieces that you and your family are sure to love.", 'format': 'Audio CD', 'link': 'https://www.goodreads.com/book/show/3209316-emma', 'authors': [{'author_id': '1265', 'role': ''}], 'publisher': 'Brilliance Audio', 'num_pages': '544', 'publication_day': '25', 'isbn13': '9781597371285', 'publication_month': '9', 'edition_information': '', 'publication_year': '2005', 'url': 'https://www.goodreads.com/book/show/3209316-emma', 'image_url': 'https://s.gr-assets.com/assets/nophoto/book/111x148-bcc042a9c91a29c1d680899eff700a03.png', 'book_id': '3209316', 'ratings_count': '42', 'work_id': '3360164', 'title': 'Emma', 'title_without_series': 'Emma'})

In [5]:
df3 = json_bag.to_dataframe()
display(df3.head())

,isbn,text_reviews_count,series,country_code,language_code,popular_shelves,asin,is_ebook,average_rating,kindle_asin,...,publication_month,edition_information,publication_year,url,image_url,book_id,ratings_count,work_id,title,title_without_series
0,,4,[],US,,"[{'count': '4', 'name': 'to-read'}, {'count': ...",,true,3.86,,...,5,,2017,https://www.goodreads.com/book/show/34883016-p...,https://images.gr-assets.com/books/1493525974m...,34883016,5,56135087,Playmaker: A Venom Series Novella,Playmaker: A Venom Series Novella
1,,21,[811663],US,en-US,"[{'count': '598', 'name': 'to-read'}, {'count'...",B01BLJGA9S,true,4.23,B01BLJGA9S,...,,,,https://www.goodreads.com/book/show/29074693-p...,https://s.gr-assets.com/assets/nophoto/book/11...,29074693,149,46079519,"Prowled Darkness (Dante's Circle, #7)","Prowled Darkness (Dante's Circle, #7)"
2,1597371289,8,[],US,eng,"[{'count': '16215', 'name': 'classics'}, {'cou...",,false,3.99,B0083Z3O8Y,...,9,,2005,https://www.goodreads.com/book/show/3209316-emma,https://s.gr-assets.com/assets/nophoto/book/11...,3209316,42,3360164,Emma,Emma
3,,27,[938303],US,en-GB,"[{'count': '25', 'name': 'to-read'}, {'count':...",B01HX6PENG,true,4.31,B01HX6PENG,...,,,,https://www.goodreads.com/book/show/30838933-g...,https://s.gr-assets.com/assets/nophoto/book/11...,30838933,139,51437308,"Guardian Cougar (Finding Fatherhood, #2)","Guardian Cougar (Finding Fatherhood, #2)"
4,,15,[],US,eng,"[{'count': '1492', 'name': 'to-read'}, {'count...",B013Q70BQG,true,3.98,B013Q70BQG,...,,,,https://www.goodreads.com/book/show/27419760-w...,https://images.gr-assets.com/books/1457306424m...,27419760,167,46003673,Wedding Girl,Wedding Girl

In [6]:
df3 = df3[df3['book_id'].notnull()]
df3.head()

,isbn,text_reviews_count,series,country_code,language_code,popular_shelves,asin,is_ebook,average_rating,kindle_asin,...,publication_month,edition_information,publication_year,url,image_url,book_id,ratings_count,work_id,title,title_without_series
0,,4,[],US,,"[{'count': '4', 'name': 'to-read'}, {'count': ...",,true,3.86,,...,5,,2017,https://www.goodreads.com/book/show/34883016-p...,https://images.gr-assets.com/books/1493525974m...,34883016,5,56135087,Playmaker: A Venom Series Novella,Playmaker: A Venom Series Novella
1,,21,[811663],US,en-US,"[{'count': '598', 'name': 'to-read'}, {'count'...",B01BLJGA9S,true,4.23,B01BLJGA9S,...,,,,https://www.goodreads.com/book/show/29074693-p...,https://s.gr-assets.com/assets/nophoto/book/11...,29074693,149,46079519,"Prowled Darkness (Dante's Circle, #7)","Prowled Darkness (Dante's Circle, #7)"
2,1597371289,8,[],US,eng,"[{'count': '16215', 'name': 'classics'}, {'cou...",,false,3.99,B0083Z3O8Y,...,9,,2005,https://www.goodreads.com/book/show/3209316-emma,https://s.gr-assets.com/assets/nophoto/book/11...,3209316,42,3360164,Emma,Emma
3,,27,[938303],US,en-GB,"[{'count': '25', 'name': 'to-read'}, {'count':...",B01HX6PENG,true,4.31,B01HX6PENG,...,,,,https://www.goodreads.com/book/show/30838933-g...,https://s.gr-assets.com/assets/nophoto/book/11...,30838933,139,51437308,"Guardian Cougar (Finding Fatherhood, #2)","Guardian Cougar (Finding Fatherhood, #2)"
4,,15,[],US,eng,"[{'count': '1492', 'name': 'to-read'}, {'count...",B013Q70BQG,true,3.98,B013Q70BQG,...,,,,https://www.goodreads.com/book/show/27419760-w...,https://images.gr-assets.com/books/1457306424m...,27419760,167,46003673,Wedding Girl,Wedding Girl

In [7]:
'''df3 = df3[df3['language_code'].str.contains('en|eng|en-GB|en-US|en-CA')]'''

IndexingError: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match).

In [8]:
df3 = df3.compute()

In [9]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 335449 entries, 0 to 335448
Data columns (total 29 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   isbn                  335449 non-null  object
 1   text_reviews_count    335449 non-null  object
 2   series                335449 non-null  object
 3   country_code          335449 non-null  object
 4   language_code         335449 non-null  object
 5   popular_shelves       335449 non-null  object
 6   asin                  335449 non-null  object
 7   is_ebook              335449 non-null  object
 8   average_rating        335449 non-null  object
 9   kindle_asin           335449 non-null  object
 10  similar_books         335449 non-null  object
 11  description           335449 non-null  object
 12  format                335449 non-null  object
 13  link                  335449 non-null  object
 14  authors               335449 non-null  object
 15  publisher             335449 non-null  object
 16  num_pages             335449 non-null  object
 17  publication_day       335449 non-null  object
 18  isbn13                335449 non-null  object
 19  publication_month     335449 non-null  object
 20  edition_information   335449 non-null  object
 21  publication_year      335449 non-null  object
 22  url                   335449 non-null  object
 23  image_url             335449 non-null  object
 24  book_id               335449 non-null  object
 25  ratings_count         335449 non-null  object
 26  work_id               335449 non-null  object
 27  title                 335449 non-null  object
 28  title_without_series  335449 non-null  object
dtypes: object(29)
memory usage: 74.2+ MB

In [ ]:
#df3.head().to_csv('testdata.csv')

In [10]:
df4 = df3.drop(['popular_shelves','link','url','image_url','title_without_series'], axis = 1)

In [11]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 335449 entries, 0 to 335448
Data columns (total 24 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   isbn                 335449 non-null  object
 1   text_reviews_count   335449 non-null  object
 2   series               335449 non-null  object
 3   country_code         335449 non-null  object
 4   language_code        335449 non-null  object
 5   asin                 335449 non-null  object
 6   is_ebook             335449 non-null  object
 7   average_rating       335449 non-null  object
 8   kindle_asin          335449 non-null  object
 9   similar_books        335449 non-null  object
 10  description          335449 non-null  object
 11  format               335449 non-null  object
 12  authors              335449 non-null  object
 13  publisher            335449 non-null  object
 14  num_pages            335449 non-null  object
 15  publication_day      335449 non-null  object
 16  isbn13               335449 non-null  object
 17  publication_month    335449 non-null  object
 18  edition_information  335449 non-null  object
 19  publication_year     335449 non-null  object
 20  book_id              335449 non-null  object
 21  ratings_count        335449 non-null  object
 22  work_id              335449 non-null  object
 23  title                335449 non-null  object
dtypes: object(24)
memory usage: 61.4+ MB

In [ ]:
df4.to_csv('rombook_data.csv')

## Converting goodreads_reviews_romance from json to csv

In [12]:
json_bag = db.read_text('goodreads_reviews_romance.json').map(json.loads)
print(json_bag.take(3))

({'user_id': '8842281e1d1347389f2ab93d60773d4d', 'book_id': '1893', 'review_id': '5347a776a1703b823ce029d68ae98275', 'rating': 5, 'review_text': "** spoiler alert ** \n So the other day Elizabeth and I are in the book store and she saw this book, and said she really wanted me to read it. In horror at the thought of reading what I thought was a 'chick book', i immediately countered that she would then have to read one of my favorites: Dune. She agreed! \n So I read it, and I have to admit, it was good - damn good. Even though there was a serious lack of any gratuitous violence, I tore through it in several days. Austen is an amazing writer, and has a particular talent for explaining her characters deep motivations (or prejudices) in a few defining sentences. \n I think my favorite part of it is the unwinding of Elizabeths' prejudices against Mr Darcy. It is done so slowly and artfully and believably that the reader is completely pulled into the story. \n It is a definite period piece - here are a few funny observations: \n - Nobody in the book had a job - they all earned income from their estates \n - Since nobody had jobs they spent all day gossiping \n - People were judged not by what they did for a living but what family they were from and how they behaved in society. Completely different from today! \n - Dating was much tougher back then. You needed at least 10 dates to get anywhere, and you probably had to marry in order to go all the way. \n Jokes aside, this is a classic, and I highly recommend it for any guy or girl.", 'date_added': 'Tue Oct 10 19:08:05 -0700 2006', 'date_updated': 'Sun Feb 19 02:04:48 -0800 2017', 'read_at': 'Sun Oct 01 00:00:00 -0700 2006', 'started_at': '', 'n_votes': 155, 'n_comments': 4}, {'user_id': '72fb0d0087d28c832f15776b0d936598', 'book_id': '17939501', 'review_id': '719711cc71eec0bb54d2d97322c0e11b', 'rating': 5, 'review_text': 'It is very hard to believe this is all true, but I\'ll take the author\'s word for it! \n I\'ve always had an open mind toward women who choose to work in this trade and a lot of compassion. I feel that often there is desperation in making the choice to sell your body, as shown by this story. \n I feel like the story at times aimed to be "sexy" rather than "sexual", if that makes sense. I feel that took away from the biographical focus and edged on erotica. However, it didn\'t effect my overall opinion greatly. I couldn\'t put it down and not because of licentious reasons, but simply because I wanted to know what happened next in this woman\'s life!', 'date_added': 'Fri Nov 08 20:17:30 -0800 2013', 'date_updated': 'Fri Nov 08 20:22:59 -0800 2013', 'read_at': '', 'started_at': '', 'n_votes': 0, 'n_comments': 0}, {'user_id': '72fb0d0087d28c832f15776b0d936598', 'book_id': '15706923', 'review_id': '6a870a66f732183b60214d57fa553093', 'rating': 2, 'review_text': 'Ehhhhhh. \n Really nothing to rave about. It was not poorly written in terms of style or technical aspects. The story was not particularly interesting and I feel it is a bit overdone. It does not stand out from other vampire fiction to me. The "romance" happened far too quickly, in my opinion. I would expect vampires who have lived so long to be a little harder to get in the sack, but... Even for a short story, it was short. \n I feel like the author is capable of more. I would like to see a longer story from her. :)', 'date_added': 'Fri Nov 08 20:14:53 -0800 2013', 'date_updated': 'Fri Nov 08 20:16:50 -0800 2013', 'read_at': '', 'started_at': '', 'n_votes': 0, 'n_comments': 0})

In [13]:
df = json_bag.to_dataframe()
display(df.head())

,user_id,book_id,review_id,rating,review_text,date_added,date_updated,read_at,started_at,n_votes,n_comments
0,8842281e1d1347389f2ab93d60773d4d,1893,5347a776a1703b823ce029d68ae98275,5,** spoiler alert ** \n So the other day Elizab...,Tue Oct 10 19:08:05 -0700 2006,Sun Feb 19 02:04:48 -0800 2017,Sun Oct 01 00:00:00 -0700 2006,,155,4
1,72fb0d0087d28c832f15776b0d936598,17939501,719711cc71eec0bb54d2d97322c0e11b,5,"It is very hard to believe this is all true, b...",Fri Nov 08 20:17:30 -0800 2013,Fri Nov 08 20:22:59 -0800 2013,,,0,0
2,72fb0d0087d28c832f15776b0d936598,15706923,6a870a66f732183b60214d57fa553093,2,Ehhhhhh. \n Really nothing to rave about. It w...,Fri Nov 08 20:14:53 -0800 2013,Fri Nov 08 20:16:50 -0800 2013,,,0,0
3,72fb0d0087d28c832f15776b0d936598,7840190,f73a70f64564d4a8f4cfb2d2e9d5836f,4,Enjoyable read! I liked that Connie is not a t...,Fri Nov 08 19:57:47 -0800 2013,Fri Nov 08 20:01:41 -0800 2013,,,0,0
4,72fb0d0087d28c832f15776b0d936598,15463724,547aeff3c7ee5b4a39a93cd2a720b001,4,There are definitely too many books lately wit...,Wed Oct 30 11:19:32 -0700 2013,Wed Oct 30 11:20:53 -0700 2013,,,0,0

In [ ]:
df.to_csv('goodreads_romreviews_data.csv')

In [17]:
df2 = df[df['book_id'].notnull()]
df2.head()

,user_id,book_id,review_id,rating,review_text,date_added,date_updated,read_at,started_at,n_votes,n_comments
0,8842281e1d1347389f2ab93d60773d4d,1893,5347a776a1703b823ce029d68ae98275,5,** spoiler alert ** \n So the other day Elizab...,Tue Oct 10 19:08:05 -0700 2006,Sun Feb 19 02:04:48 -0800 2017,Sun Oct 01 00:00:00 -0700 2006,,155,4
1,72fb0d0087d28c832f15776b0d936598,17939501,719711cc71eec0bb54d2d97322c0e11b,5,"It is very hard to believe this is all true, b...",Fri Nov 08 20:17:30 -0800 2013,Fri Nov 08 20:22:59 -0800 2013,,,0,0
2,72fb0d0087d28c832f15776b0d936598,15706923,6a870a66f732183b60214d57fa553093,2,Ehhhhhh. \n Really nothing to rave about. It w...,Fri Nov 08 20:14:53 -0800 2013,Fri Nov 08 20:16:50 -0800 2013,,,0,0
3,72fb0d0087d28c832f15776b0d936598,7840190,f73a70f64564d4a8f4cfb2d2e9d5836f,4,Enjoyable read! I liked that Connie is not a t...,Fri Nov 08 19:57:47 -0800 2013,Fri Nov 08 20:01:41 -0800 2013,,,0,0
4,72fb0d0087d28c832f15776b0d936598,15463724,547aeff3c7ee5b4a39a93cd2a720b001,4,There are definitely too many books lately wit...,Wed Oct 30 11:19:32 -0700 2013,Wed Oct 30 11:20:53 -0700 2013,,,0,0

In [18]:
df2.shape

(<dask_expr.expr.Scalar: expr=(Filter(frame=FromGraph(6a5da95), predicate=NotNull(frame=FromGraph(6a5da95)['book_id']))).size() // 11, dtype=int64>,
 11)

In [ ]:
df5.info()

In [22]:
df3.shape

(335449, 29)

In [23]:
df2.compute()

,user_id,book_id,review_id,rating,review_text,date_added,date_updated,read_at,started_at,n_votes,n_comments
0,8842281e1d1347389f2ab93d60773d4d,1893,5347a776a1703b823ce029d68ae98275,5,** spoiler alert ** \n So the other day Elizab...,Tue Oct 10 19:08:05 -0700 2006,Sun Feb 19 02:04:48 -0800 2017,Sun Oct 01 00:00:00 -0700 2006,,155,4
1,72fb0d0087d28c832f15776b0d936598,17939501,719711cc71eec0bb54d2d97322c0e11b,5,"It is very hard to believe this is all true, b...",Fri Nov 08 20:17:30 -0800 2013,Fri Nov 08 20:22:59 -0800 2013,,,0,0
2,72fb0d0087d28c832f15776b0d936598,15706923,6a870a66f732183b60214d57fa553093,2,Ehhhhhh. \n Really nothing to rave about. It w...,Fri Nov 08 20:14:53 -0800 2013,Fri Nov 08 20:16:50 -0800 2013,,,0,0
3,72fb0d0087d28c832f15776b0d936598,7840190,f73a70f64564d4a8f4cfb2d2e9d5836f,4,Enjoyable read! I liked that Connie is not a t...,Fri Nov 08 19:57:47 -0800 2013,Fri Nov 08 20:01:41 -0800 2013,,,0,0
4,72fb0d0087d28c832f15776b0d936598,15463724,547aeff3c7ee5b4a39a93cd2a720b001,4,There are definitely too many books lately wit...,Wed Oct 30 11:19:32 -0700 2013,Wed Oct 30 11:20:53 -0700 2013,,,0,0
...,...,...,...,...,...,...,...,...,...,...,...
3565373,c5ae39ab55f5031b440d93f3f09ee736,13548195,4a652ea59c5d68caa4ac9ec5fecbf2b2,5,"Catherine Miller, the heroine of the story is ...",Fri Jun 28 11:29:21 -0700 2013,Fri Jun 28 11:29:40 -0700 2013,,,0,0
3565374,c5ae39ab55f5031b440d93f3f09ee736,13261268,494baf5b0cfd4f8bf7d6f405ec6895f8,5,Broken Trust by Sharon Dunn is a romantic susp...,Fri Jun 28 09:07:53 -0700 2013,Fri Jun 28 09:08:21 -0700 2013,,,0,0
3565375,c5ae39ab55f5031b440d93f3f09ee736,16109790,81c9b870a37544175a76abda0f171eaa,4,The book will appeal to those who enjoy romanc...,Sun May 26 17:42:03 -0700 2013,Thu Jul 25 15:11:42 -0700 2013,Fri Jul 19 00:00:00 -0700 2013,Sun May 26 00:00:00 -0700 2013,0,0
3565376,8ba77e3c745ebddccc6306fc3c6bb25e,20410348,29602f049f9a7f7e525886613e3b2b50,5,I wrote 7-8 novels (so many I've lost count) b...,Sun Jul 08 16:24:55 -0700 2012,Mon Sep 21 07:32:04 -0700 2015,Wed May 16 00:00:00 -0700 2012,,3,2
3565377,d0f6d1a4edcab80a6010cfcfeda4999f,3412,15b03b5fbbda45ac93a9729fa3faf2f2,5,Truly a remarkable read......Meggie is your do...,Mon Jul 30 16:08:09 -0700 2012,Mon Jul 30 16:14:46 -0700 2012,Wed Apr 06 00:00:00 -0700 2011,,0,0